name: Build

on:
  push:
    branches: ['*']

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com
          scope: '@oriumnetwork'
      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHB_TOKEN }}
      - name: Lint
        run: npm run lint
      - name: Compile Smart Contracts
        run: npm run compile
      - name: Test Coverage
        run: npm run coverage
